/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CafeRestaurentSystem;

import java.awt.print.PrinterException;
//import java.lang.System.Logger;
//import java.lang.System.Logger.Level;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
//import java.util.Calendar;
//import java.util.GregorianCalendar;


/**
 *
 * @author Tushar Hasan
 */
public class CaferRestaurent extends javax.swing.JFrame {
   double [] drink = new double[5];
   double [] cakes =new double[5];
   double drinkCost=0;
   double cakeCost=0;
   double []drinkPrice ={110,130,100,150,175};
   double []cakeprice={180,210,250,280,350};
    /**
     * Creates new form CaferRestaurent
     */
    public CaferRestaurent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        icon2 = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        taxtf = new javax.swing.JTextField();
        subtf = new javax.swing.JTextField();
        totaltf = new javax.swing.JTextField();
        tax = new javax.swing.JLabel();
        sub = new javax.swing.JLabel();
        taotal = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btprint = new javax.swing.JButton();
        bttotal = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        fruit2 = new javax.swing.JLabel();
        pound2 = new javax.swing.JLabel();
        red2 = new javax.swing.JLabel();
        cheese2 = new javax.swing.JLabel();
        black2 = new javax.swing.JLabel();
        poundtf = new javax.swing.JTextField();
        redtf = new javax.swing.JTextField();
        fruittf = new javax.swing.JTextField();
        cheesetf = new javax.swing.JTextField();
        blacktf = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rcpt = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        coffe2 = new javax.swing.JLabel();
        latte2 = new javax.swing.JLabel();
        espresso2 = new javax.swing.JLabel();
        cuppuccino2 = new javax.swing.JLabel();
        mocha2 = new javax.swing.JLabel();
        lattetf = new javax.swing.JTextField();
        espressotf = new javax.swing.JTextField();
        coffetf = new javax.swing.JTextField();
        cuppuccinotf = new javax.swing.JTextField();
        mochatf = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        cakecosttf = new javax.swing.JTextField();
        drinkcosttf = new javax.swing.JTextField();
        servicetf = new javax.swing.JTextField();
        cakecost3 = new javax.swing.JLabel();
        cakecost4 = new javax.swing.JLabel();
        cakecost5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));
        setForeground(new java.awt.Color(153, 255, 255));
        setPreferredSize(new java.awt.Dimension(1300, 720));
        setSize(new java.awt.Dimension(1300, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("NSU CAFE & Restaurent   ");

        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/Food-Hot-Chocolate-icon.png"))); // NOI18N

        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/City-Restaurant-icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(icon2)
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icon2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(icon1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1270, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N

        taxtf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        taxtf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        taxtf.setText("0.0");
        taxtf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        subtf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subtf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        subtf.setText("0.0");
        subtf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        totaltf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totaltf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totaltf.setText("0.0");
        totaltf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        tax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tax.setText("Tax");

        sub.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sub.setText("Sub Total");

        taotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        taotal.setText("Total");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tax, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taotal, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(taxtf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(subtf, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totaltf, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tax, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taxtf, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtf, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(taotal, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(totaltf))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 350, 270));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel4.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N

        btprint.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btprint.setText("Print");
        btprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btprintActionPerformed(evt);
            }
        });

        bttotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bttotal.setText("Total");
        bttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttotalActionPerformed(evt);
            }
        });

        reset.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(bttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btprint, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btprint, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 590, 560, 80));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel5.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N

        fruit2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fruit2.setText("Fruit Cake");

        pound2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pound2.setText("Pound Cake");

        red2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        red2.setText("Red Velvate Cake");

        cheese2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cheese2.setText("Cheese Cake");

        black2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        black2.setText("Black Forest Cake");

        poundtf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poundtf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        poundtf.setText("0");
        poundtf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        redtf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        redtf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        redtf.setText("0");
        redtf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        fruittf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fruittf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fruittf.setText("0");
        fruittf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        cheesetf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cheesetf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cheesetf.setText("0");
        cheesetf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        blacktf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        blacktf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        blacktf.setText("0");
        blacktf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pound2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fruit2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cheese2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(poundtf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fruittf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cheesetf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(black2, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(red2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(redtf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blacktf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pound2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poundtf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(red2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(redtf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fruit2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fruittf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cheese2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cheesetf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(black2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blacktf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 350, 270));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel6.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N

        rcpt.setColumns(20);
        rcpt.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        rcpt.setRows(5);
        jScrollPane1.setViewportView(rcpt);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, 560, 460));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel7.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N

        coffe2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        coffe2.setText("Black Coffe");

        latte2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        latte2.setText("Latte");

        espresso2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        espresso2.setText("Espresso");

        cuppuccino2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cuppuccino2.setText("Cappuccino");

        mocha2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mocha2.setText("Mocha Latte");

        lattetf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lattetf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lattetf.setText("0");
        lattetf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        espressotf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        espressotf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        espressotf.setText("0");
        espressotf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        coffetf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        coffetf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        coffetf.setText("0");
        coffetf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        cuppuccinotf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cuppuccinotf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cuppuccinotf.setText("0");
        cuppuccinotf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        mochatf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mochatf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mochatf.setText("0");
        mochatf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(latte2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cuppuccino2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coffe2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lattetf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coffetf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cuppuccinotf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(mocha2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mochatf, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(espresso2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(espressotf, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(latte2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lattetf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(espresso2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(espressotf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coffe2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coffetf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuppuccino2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuppuccinotf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mocha2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mochatf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 340, 270));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel8.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N

        cakecosttf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cakecosttf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cakecosttf.setText("0.0");
        cakecosttf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        cakecosttf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cakecosttfActionPerformed(evt);
            }
        });

        drinkcosttf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        drinkcosttf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        drinkcosttf.setText("0.0");
        drinkcosttf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        servicetf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        servicetf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        servicetf.setText("0.0");
        servicetf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        cakecost3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cakecost3.setText("Cost of Cakes ");

        cakecost4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cakecost4.setText("Cost of Drinks");

        cakecost5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cakecost5.setText("Service Charge ");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cakecost3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cakecost4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cakecost5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cakecosttf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drinkcosttf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(servicetf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cakecost3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cakecosttf, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cakecost4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drinkcosttf, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cakecost5, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(servicetf))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 340, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        JFrame frame; 
        frame = new JFrame();
            if(JOptionPane.showConfirmDialog(frame,"Are you sure?","NSU CAFE & RAETAURANT",
                    JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION) {
                System.exit(0);
            }
    }//GEN-LAST:event_exitActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        fullreset();
        
    }//GEN-LAST:event_resetActionPerformed
    private void fullreset(){
        double treset =0;
        String ireset =String.format("%.1f",treset);
        String reset =String.format("%.0f",treset);
        
        lattetf.setText(reset);
        espressotf.setText(reset);
        coffetf.setText(reset);
        cuppuccinotf.setText(reset);
        mochatf.setText(reset);
                      
                      
        poundtf.setText(reset);
        redtf.setText(reset);
        fruittf.setText(reset);
        cheesetf.setText(reset);
        blacktf.setText(reset);
                     
        cakecosttf.setText(ireset);
        drinkcosttf.setText(ireset);
        servicetf.setText(ireset);
        taxtf.setText(ireset);
        subtf.setText(ireset);
        totaltf.setText(ireset);
                                 
        rcpt.setText(null);
        drinkCost=0;
        cakeCost=0;
    }
    private void bttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttotalActionPerformed
        // TODO add your handling code here:
        try{
        //rcpt.setText(null);
        
        drink[0]=Double.parseDouble(lattetf.getText());
        drink[1]=Double.parseDouble(espressotf.getText());
        drink[2]=Double.parseDouble(coffetf.getText());
        drink[3]=Double.parseDouble(cuppuccinotf.getText());
        drink[4]=Double.parseDouble(mochatf.getText());
        
        cakes[0]=Double.parseDouble(poundtf.getText());
        cakes[1]=Double.parseDouble(redtf.getText());
        cakes[2]=Double.parseDouble(fruittf.getText());
        cakes[3]=Double.parseDouble(cheesetf.getText());
        cakes[4]=Double.parseDouble(blacktf.getText());
        
        for(int i=0;i<drink.length;i++)
       {
           drinkCost+=(drink[i]*drinkPrice[i]);
       }
       for(int i=0;i<cakes.length;i++)
       {
           cakeCost+=(cakes[i]*cakeprice[i]);
       }
       
       double tax = (drinkCost+cakeCost)*(08.00/100.00);
       double service_charge = 0;
      
       if((drinkCost+cakeCost)<1000 && (drinkCost+cakeCost)!=0)
       {
           service_charge=30;
       }
       
        double sub_total=drinkCost+cakeCost;
        double total = sub_total+tax+service_charge;;
        int rtotal=(int) (total+0.5);
        
        cakecosttf.setText(String.valueOf(Double.toString(drinkCost)));
        drinkcosttf.setText(String.valueOf(Double.toString(cakeCost)));
        servicetf.setText(String.valueOf(Double.toString(service_charge)));
         
        taxtf.setText(String.valueOf(Double.toString(tax)));
        subtf.setText(String.valueOf(Double.toString(sub_total)));
        totaltf.setText(String.valueOf(Double.toString(total)));
        
        //////////////////////Bill Information in Screen///////////////////////
        rcpt.append("\t\t    NSU Cafe & Restaurent"+
                  "\n\n"+"Product\t\t"+"Unit Price\t"+"Quantity\t\t"+"Price"+
                  "\n"+
                 "\nLatte\t\t"+"      110\t      " +(int)(drink[0])+"\t\t"+(drink[0]*drinkPrice[0])
                +"\nEspresso\t\t"+"      130\t      "+(int)drink[1]+"\t\t"+(drink[1]*drinkPrice[1])
                 +"\nBlack coffe\t\t"+"      100\t      "+(int)drink[2]+"\t\t"+(drink[2]*drinkPrice[2])
                +"\nCappaccino\t\t"+"      150\t      "+(int)drink[3]+"\t\t"+(drink[3]*drinkPrice[3])
                +"\nMocha Latte\t\t"+"      170\t      "+(int)drink[4]+"\t\t"+(drink[4]*drinkPrice[4])
                +"\n"+
                 "\nPound Cake\t\t"+"      180\t      "+(int)cakes[0]+"\t\t"+(cakes[0]*cakeprice[0])
                + "\nRed Valvate Cake\t"+"      210\t      "+(int)cakes[1]+"\t\t"+(cakes[1]*cakeprice[1])
                +"\nFruit Cake\t\t"+"      250\t      "+(int)cakes[2]+"\t\t"+(cakes[2]*cakeprice[2])
                 +"\nChiffon Cake\t\t"+"      280\t      "+(int)cakes[3]+"\t\t"+(cakes[3]*cakeprice[3])
                +"\nBlack Forest Cake\t"+"      350\t      "+(int)cakes[4]+"\t\t"+(cakes[4]*cakeprice[4])
                +"\n==================================================================="
                +"\n\nTotal Drink Cost\t"+drinkCost+"\tTaka"
                +"\nTotal Cake Cost\t\t"+cakeCost+"\tTaka"
                +"\nService Charge\t\t"+service_charge+"\tTaka"
                +"\nTax\t\t"+tax+"\tTaka"
                +"\n\nToatal(rounded)\t"+(int)(total+.5)+"\tTaka"
                        
                +"\n\n\t\t                   Thank You" );
        }
        catch(NumberFormatException ex)
       {
           JOptionPane.showMessageDialog(null, 
            "Input Valid Info!",
            "NSU CAFE RESTAURANT",    
            JOptionPane.INFORMATION_MESSAGE);
            fullreset();
            
       }
        
        
               
    }//GEN-LAST:event_bttotalActionPerformed

    private void cakecosttfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cakecosttfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cakecosttfActionPerformed

    private void btprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btprintActionPerformed
        // TODO add your handling code here:
        try{
            rcpt.print();
        }catch(PrinterException ex)
        {
          java.util.logging.Logger.getLogger(CaferRestaurent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  }
    }//GEN-LAST:event_btprintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaferRestaurent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaferRestaurent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaferRestaurent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaferRestaurent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaferRestaurent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel black2;
    private javax.swing.JTextField blacktf;
    private javax.swing.JButton btprint;
    private javax.swing.JButton bttotal;
    private javax.swing.JLabel cakecost3;
    private javax.swing.JLabel cakecost4;
    private javax.swing.JLabel cakecost5;
    private javax.swing.JTextField cakecosttf;
    private javax.swing.JLabel cheese2;
    private javax.swing.JTextField cheesetf;
    private javax.swing.JLabel coffe2;
    private javax.swing.JTextField coffetf;
    private javax.swing.JLabel cuppuccino2;
    private javax.swing.JTextField cuppuccinotf;
    private javax.swing.JTextField drinkcosttf;
    private javax.swing.JLabel espresso2;
    private javax.swing.JTextField espressotf;
    private javax.swing.JButton exit;
    private javax.swing.JLabel fruit2;
    private javax.swing.JTextField fruittf;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel latte2;
    private javax.swing.JTextField lattetf;
    private javax.swing.JLabel mocha2;
    private javax.swing.JTextField mochatf;
    private javax.swing.JLabel pound2;
    private javax.swing.JTextField poundtf;
    private javax.swing.JTextArea rcpt;
    private javax.swing.JLabel red2;
    private javax.swing.JTextField redtf;
    private javax.swing.JButton reset;
    private javax.swing.JTextField servicetf;
    private javax.swing.JLabel sub;
    private javax.swing.JTextField subtf;
    private javax.swing.JLabel taotal;
    private javax.swing.JLabel tax;
    private javax.swing.JTextField taxtf;
    private javax.swing.JTextField totaltf;
    // End of variables declaration//GEN-END:variables
}
